[package]
name = "plugin_registry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json_dotpath = "1.0.3"
libloading = "0.6.6"
serde = "1.0.118"
serde_json = "1.0.60"
