- path: ^/foo/bar$
  responseStatus: 400
  rules:
    - path: ''
      item:


- path: ^/users/final/$
  headers:
    x-app-name: psyco
  rules:
    - path: ''
      item:
        users:
          - name: rick
            surname: sanchez
            status: doing epic stuff
          - name: morty
            surname: smith
            status: learning things

- path: ^/final/$
  forwardUri:
    "http://localhost:8888/users"
  #yamlanchor: &foobaranchor
  #  test1: "test"
  #  test2: "test"
  rules:
    - path: 'users.>>'
      item:
        #<< : *foobaranchor
        "{{UUID}}"
