[package]
name = "configuration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plugin_registry = { path = "../plugin_registry" }
bytes = "1.0.0"
serde_yaml = "0.8.14"
serde = "1.0.118"
serde_json = "1.0.60"
json-patch = "*"
regex = "1.4.2"
crossterm = "0.18"
tui = { version = "0.13", default-features = false, features = ['crossterm'] }
rand = "0.7"
unicode-width = "0.1"
futures="0.3"
tokio= { version="1.0", features=["full"] }
hyper = { version = "0.14", features = ["full"] }
json_dotpath = "1.0.3"
strum = "0.20"
strum_macros = "0.20"
libloading = "0.6.6"
